full_file<-read.csv(file="household_power_consumption.txt",sep=";",col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"),na.string="?")
full_file$Date<-strptime(paste(full_file$Date,full_file$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
real_data<-subset(full_file,Date>="2007-02-01 00:00:00" & Date<"2007-02-03 00:00:00")
png(file="plot4.png",height=480,width=480)
par(mfrow=c(2,2))
plot(real_data$Date,real_data$Global_active_power,type="l", xlab="",ylab="Global Active Power (kilowatts)")
plot(real_data$Date,real_data$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(real_data$Date,real_data$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(real_data$Date,real_data$Sub_metering_2,col="red")
lines(real_data$Date,real_data$Sub_metering_3,col="blue")
plot(real_data$Date,real_data$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()